export const BASE_URL = "https://api.aoinstore.com";

export const ROUTES = Object.freeze({
  SEND_OTP: '/api/auth/phone/send-otp',
  SING_UP: '/api/auth/phone/verify-signup',
  USER_LOGIN: '/api/auth/phone/verify-login',
  MERCHANT_LOGIN: '/api/auth/login',
  UPLOAD_REEL: '/api/reels',
  PRODUCTS_AVAILABLE: '/api/reels/products/available',
  MERCHANT_MY_REELS: '/api/reels/merchant/my',
  PUBLIC_REELS: '/api/reels/public',
  LIKE_REEL: '/api/reels',
  UNLIKE_REEL: '/api/reels',
  SHARE_REEL: '/api/reels',
  DELETE_REEL: '/api/reels',
  EDIT_REEL: '/api/reels',
  FOLLOW_MERCHANT: '/api/merchants',
  UNFOLLOW_MERCHANT: '/api/merchants',
  REELBATCHDELET: '/api/reels/batch/delete',
  MERCHANT_PROFILE: '/api/merchants/profile',
  MERCHANT_FOLLOW: '/api/merchants/{merchant_id}/follow',
  MERCHANT_UNFOLLOW: '/api/merchants/{merchant_id}/unfollow',
  MERCHANT_FOLLOW_LIST: '/api/merchants/following',
  MERCHANT_FOLLOWERS: '/api/merchants/followers',
  GET_TRENDING_LIST:'/api/reels/feed/trending',
  NOTIFICATIONS_UNREAD_COUNT: '/api/merchants/notifications/unread-count',
  NOTIFICATIONS: 'api/merchants/notifications',
  NOTIFICATION_MARK_READ: '/api/merchants/notifications',
  NOTIFICATION_MARK_ALL_READ: '/api/merchants/notifications/mark-all-read',
  NOTIFICATION_DELETE: '/api/merchants/notifications',
  NOTIFICATIONS_BULK_DELETE: '/api/merchants/notifications/bulk-delete',
  NOTIFICATIONS_CLEANUP: '/api/merchants/notifications/cleanup',
  MERCHANT_FOLLOWERS_COUNT: '/api/merchants/',
  MERCHANT_PUBLIC_PROFILE: '/api/merchants/',
  MERCHANT_STATS: '/api/reels/merchant/',
  USER_PROFILE: '/api/users/profile',
  GOOGLE_LOGIN: 'https://api.aoinstore.com/api/auth/google',
});


export const GOOGLE_CLIENT_ID = '968020800951-t89qvbb6ne0nh8oh4cne6a3blqr6gs3l.apps.googleusercontent.com'